server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

app:
  system-name: Monitoring Portal

logging:
  level:
    org.springframework.web: DEBUG
    org.thymeleaf: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://172.22.1.113:5432/monitoring
    username: monitoring
    password: monitoring
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true

  flyway:
    locations: classpath:db/migration
    repair-on-migrate: true  # 마이그레이션 파일 변경 시 체크섬 자동 수정
    baseline-on-migrate: true  # 기존 스키마가 있을 때 baseline 설정
    validate-on-migrate: false  # 마이그레이션 파일 변경 시 체크섬 불일치 허용

    logging:
      level:
        org.flywaydb: DEBUG
        org.springframework.boot.autoconfigure.flyway: DEBUG